/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/2b_Character.gltf -o src/components/Showfer2b.jsx -r public 
*/
// @ts-nocheck

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";

export default function Buddy(props) {
  const { nodes, materials } = useGLTF("/models/2b_Character.gltf");

  useEffect(() => {
    if (!props.isAudioPlaying) return;

    let animationFrameId;
    let talkValue = 0;

    const animateTalk = () => {
      if (props.isAudioPlaying) {
        // Toggle between 0 and 1
        talkValue = talkValue === 0 ? 1 : 0;

        nodes.Character_2nd.morphTargetInfluences[
          nodes.Character_2nd.morphTargetDictionary["Talk"]
        ] = talkValue;

        // Request next frame after a delay to control the speed of the animation
        animationFrameId = setTimeout(() => {
          requestAnimationFrame(animateTalk);
        }, 250); // Adjust this value to change the speed of the mouth movement
      }
    };

    animateTalk();

    return () => {
      if (animationFrameId) {
        clearTimeout(animationFrameId);
      }
    };
  }, [props.isAudioPlaying, nodes.Character_2nd]);

  useEffect(() => {
    console.log(
      "shape keys dictionary 2b",
      nodes.Character_2nd.morphTargetDictionary
    );
    console.log(
      "shape keys influences 2b",
      nodes.Character_2nd.morphTargetInfluences
    );
  }, []);

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Character_2nd"
        geometry={nodes.Character_2nd.geometry}
        material={materials.Character_2nd_Baked}
        morphTargetDictionary={nodes.Character_2nd.morphTargetDictionary}
        morphTargetInfluences={nodes.Character_2nd.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/2b_Character.gltf");
