/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/5a_Character.gltf -o components/Characters/Showfer5a.tsx -r public 
*/
// @ts-nocheck

import * as THREE from "three";
import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["5th_Character"]: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export default function Edison(props) {
  const { nodes, materials } = useGLTF(
    "/models/5a_Character.gltf"
  ) as GLTFResult;

  useEffect(() => {
    if (!props.isAudioPlaying) return;

    let animationFrameId;
    let talkValue = 0;

    const animateTalk = () => {
      if (props.isAudioPlaying) {
        // Toggle between 0 and 1
        talkValue = talkValue === 0 ? 1 : 0;

        nodes["5th_Character"].morphTargetInfluences[
          nodes["5th_Character"].morphTargetDictionary["Happy_Talk"]
        ] = talkValue;

        // Request next frame after a delay to control the speed of the animation
        animationFrameId = setTimeout(() => {
          requestAnimationFrame(animateTalk);
        }, 250); // Adjust this value to change the speed of the mouth movement
      }
    };

    animateTalk();

    return () => {
      if (animationFrameId) {
        clearTimeout(animationFrameId);
      }
    };
  }, [props.isAudioPlaying, nodes.Body]);

  useEffect(() => {
    console.log(
      "shape keys dictionary 5",
      nodes["5th_Character"].morphTargetDictionary
    );
    console.log(
      "shape keys influences 5",
      nodes["5th_Character"].morphTargetInfluences
    );

    nodes["5th_Character"].morphTargetInfluences[
      nodes["5th_Character"].morphTargetDictionary["Default_Pose_2"]
    ] = 1;
  }, []);

  return (
    <group {...props} dispose={null}>
      <mesh
        name="5th_Character"
        geometry={nodes["5th_Character"].geometry}
        material={materials["Material.001"]}
        morphTargetDictionary={nodes["5th_Character"].morphTargetDictionary}
        morphTargetInfluences={nodes["5th_Character"].morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/5a_Character.gltf");
