/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/6th_Character.gltf -o src/app/_ui/Characters/Showfer6.tsx -r public 
*/
// @ts-nocheck

import * as THREE from "three";
import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    Cube_1: THREE.Mesh;
  };
  materials: {
    Car: THREE.MeshStandardMaterial;
    Tire: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export default function Griffin(props) {
  const { nodes, materials } = useGLTF(
    "/models/6th_Character.gltf"
  ) as GLTFResult;

  useEffect(() => {
    if (!props.storyState) return;

    let animationFrameId;
    let talkValue = 0;

    const animateTalk = () => {
      if (props.storyState === "assistant") {
        // Toggle between 0 and 1
        talkValue = talkValue === 0 ? 1 : 0;

        nodes.Cube.morphTargetInfluences[
          nodes.Cube.morphTargetDictionary["Happy_Talk"]
        ] = talkValue;

        // Request next frame after a delay to control the speed of the animation
        animationFrameId = setTimeout(() => {
          requestAnimationFrame(animateTalk);
        }, 250); // Adjust this value to change the speed of the mouth movement
      }
    };

    animateTalk();

    return () => {
      if (animationFrameId) {
        clearTimeout(animationFrameId);
      }
    };
  }, [props.storyState, nodes.Body]);

  useEffect(() => {
    console.log(
      "shape keys dictionary griffin",
      nodes.Cube.morphTargetDictionary
    );
    console.log(
      "shape keys influences griffin",
      nodes.Cube.morphTargetInfluences
    );
  }, []);

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Cube"
        geometry={nodes.Cube.geometry}
        material={materials.Car}
        morphTargetDictionary={nodes.Cube.morphTargetDictionary}
        morphTargetInfluences={nodes.Cube.morphTargetInfluences}
      />
      <mesh
        name="Cube_1"
        geometry={nodes.Cube_1.geometry}
        material={materials.Tire}
        morphTargetDictionary={nodes.Cube_1.morphTargetDictionary}
        morphTargetInfluences={nodes.Cube_1.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/6th_Character.gltf");
