/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/4d_Character.gltf -o components/Characters/Showfer4d.tsx -r public 
*/
// @ts-nocheck

import * as THREE from "three";
import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["4th_Character"]: THREE.Mesh;
  };
  materials: {
    material_atlas_00002_1: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export default function Imogen(props) {
  const { nodes, materials } = useGLTF(
    "/models/4d_Character.gltf"
  ) as GLTFResult;

  useEffect(() => {
    if (!props.isAudioPlaying) return;

    let animationFrameId;
    let talkValue = 0;

    const animateTalk = () => {
      if (props.isAudioPlaying) {
        // Toggle between 0 and 1
        talkValue = talkValue === 0 ? 1 : 0;

        nodes["4th_Character"].morphTargetInfluences[
          nodes["4th_Character"].morphTargetDictionary["Happy_Talk"]
        ] = talkValue;

        // Request next frame after a delay to control the speed of the animation
        animationFrameId = setTimeout(() => {
          requestAnimationFrame(animateTalk);
        }, 250); // Adjust this value to change the speed of the mouth movement
      }
    };

    animateTalk();

    return () => {
      if (animationFrameId) {
        clearTimeout(animationFrameId);
      }
    };
  }, [props.isAudioPlaying, nodes.Body]);

  useEffect(() => {
    console.log(
      "shape keys dictionary 4",
      nodes["4th_Character"].morphTargetDictionary
    );
    console.log(
      "shape keys influences 4",
      nodes["4th_Character"].morphTargetInfluences
    );

    nodes["4th_Character"].morphTargetInfluences[
      nodes["4th_Character"].morphTargetDictionary["Default_Pose"]
    ] = 1;

    // nodes.Character_1st.morphTargetInfluences[0] = 1;
    // nodes.Character_1st.morphTargetInfluences[8] = 1;
    // // nodes.Character_1st.morphTargetInfluences[0] = 1
    // // nodes.Character_1st.morphTargetInfluences[4] = 1
  }, []);

  return (
    <group {...props} dispose={null}>
      <mesh
        name="4th_Character"
        geometry={nodes["4th_Character"].geometry}
        material={materials.material_atlas_00002_1}
        morphTargetDictionary={nodes["4th_Character"].morphTargetDictionary}
        morphTargetInfluences={nodes["4th_Character"].morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/4d_Character.gltf");
