/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/3c_Character.gltf -o components/Characters/Showfer3c.tsx -r public 
*/
// @ts-nocheck

import * as THREE from "three";
import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["3rd_Character"]: THREE.Mesh;
  };
  materials: {
    material_atlas_00001_1: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export default function Sassy(props) {
  const { nodes, materials } = useGLTF(
    "/models/3c_Character.gltf"
  ) as GLTFResult;

  useEffect(() => {
    if (!props.storyState) return;

    let animationFrameId;
    let talkValue = 0;

    const animateTalk = () => {
      if (props.storyState === "assistant") {
        // Toggle between 0 and 1
        talkValue = talkValue === 0 ? 1 : 0;

        nodes["3rd_Character"].morphTargetInfluences[
          nodes["3rd_Character"].morphTargetDictionary["Happy_Talk"]
        ] = talkValue;

        // Request next frame after a delay to control the speed of the animation
        animationFrameId = setTimeout(() => {
          requestAnimationFrame(animateTalk);
        }, 250); // Adjust this value to change the speed of the mouth movement
      }
    };

    animateTalk();

    return () => {
      if (animationFrameId) {
        clearTimeout(animationFrameId);
      }
    };
  }, [props.storyState, nodes["3rd_Character"]]);

  useEffect(() => {
    console.log(
      "shape keys dictionary 3",
      nodes["3rd_Character"].morphTargetDictionary
    );
    console.log(
      "shape keys influences 3",
      nodes["3rd_Character"].morphTargetInfluences
    );

    nodes["3rd_Character"].morphTargetInfluences[
      nodes["3rd_Character"].morphTargetDictionary["Default_Pose"]
    ] = 1;
  }, []);

  return (
    <group {...props} dispose={null}>
      <mesh
        name="3rd_Character"
        geometry={nodes["3rd_Character"].geometry}
        material={materials.material_atlas_00001_1}
        morphTargetDictionary={nodes["3rd_Character"].morphTargetDictionary}
        morphTargetInfluences={nodes["3rd_Character"].morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/3c_Character.gltf");
